<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Version>1.0.0</Version>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>mouse_nudge</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="app.ico" LogicalName="mouse_nudge.app.ico" />
  </ItemGroup>

</Project>
